name: Sync with upstream
on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Pull & merge upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.PERSONAL_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: sindresorhus/caprine

      - name: Check for a new release upstream
        id: check-for-release
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://github.com/sindresorhus/caprine.git

      - name: Create a tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.check-for-release.outputs.tag }}
          message: "Latest release"
  build:
    needs: [sync]
    uses: ./.github/workflows/build.yml
